---
scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - side_effect
    - verify
    - cleanup
    - destroy
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu-${UBUNTU_RELEASE}
    image: srv6d/ubuntu-systemd:${UBUNTU_RELEASE}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    privileged: true
    command: /sbin/init
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    side_effect: side_effect.yml
    cleanup: cleanup.yml
  inventory:
    group_vars:
      all:
        gitlab_runner_ci_server_url: https://gitlab.com
        gitlab_runner_registration_token: ${RUNNER_REGISTRATION_TOKEN}
        gitlab_runner_tags: [runner, test, initial, tags]
verifier:
  name: testinfra
