---
name: Molecule Tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: 30 20 2 * *
env:
  RUNNER_REGISTRATION_TOKEN: ${{ secrets.RUNNER_REGISTRATION_TOKEN }}
jobs:
  molecule-test:
    runs-on: ubuntu-20.04
    environment: testing
    strategy:
      fail-fast: false
      matrix:
        include:
          - role: gitlab
            scenario: default
            edition: community
            release: focal
          - role: gitlab
            scenario: default
            edition: community
            release: jammy
          - role: gitlab
            scenario: default
            edition: enterprise
            release: focal
          - role: gitlab
            scenario: default
            edition: enterprise
            release: jammy
          - role: gitlab
            scenario: blocked_root_user
            edition: community
            release: focal
          - role: gitlab
            scenario: blocked_root_user
            edition: community
            release: jammy
          - role: gitlab
            scenario: blocked_root_user
            edition: enterprise
            release: focal
          - role: gitlab
            scenario: blocked_root_user
            edition: enterprise
            release: jammy
          - role: runner
            scenario: default
            edition: undefined
            release: focal
          - role: runner
            scenario: default
            edition: undefined
            release: jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: install collection pip requirements
        run: pip3 install -r requirements.txt
      - name: install testing pip requirements
        run: pip3 install -r .github/molecule-requirements.txt
      - name: run molecule tests
        run: molecule test -s ${{ matrix.scenario }}
        working-directory: roles/${{ matrix.role }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          GITLAB_EDITION: ${{ matrix.edition}}
          UBUNTU_RELEASE: ${{ matrix.release }}
