---
name: Code Style
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: lint YAML
        uses: ibiqlik/action-yamllint@v3
      - name: lint Ansible
        uses: ansible-community/ansible-lint-action@v6.16.0
